### PR TITLE
Add parameter to allow cross origin calls

### PR DESCRIPTION
**Pull request by scyv**
Hello,

i have a suggestion here to add a parameter to allow cross origin calls (CORS).

### CODE REVIEW

**Comment by sanyueyu** [comment]
thanks

**Comment by sauban** [comment]
Hello,
 please I don't see this particular changes in the latest gulp-mock-server npm module (which is 1.1.2), when I installed it.
I am using node 6.2.2
I am having the same issue as issue #18 which I believe this PR is the fix.

**Comment by sanyueyu** [comment]
please try to set "allowCrossOrigin : true" in the config ?

**Comment by sauban** [comment]
@sanyueyu  I have set the "allowCrossOrigin:true" in the config, but that doesn't seem to be the problem.
When I checked the mock.js package I am seeing this below... Which is not the current way the mock.js file is here on this repo. 

screen shot 2017-01-11 at 8 53 25 pm

Thanks.

**Comment by sanyueyu** [comment]
thanks your help, I publish version@1.1.3

**Pull request merged**
